reddit/config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'

  get 'posts/create'

  get 'posts/show'

  get 'posts/edit'

  get 'posts/update'

  get 'posts/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :subs, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub

  def author_username
    author.username
  end
end

reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :sub, :post, presence: true
  validates :post, uniqueness: { scope: :sub }

  belongs_to :sub
  belongs_to :post
end

reddit/app/models/sub.rb
class Sub < ApplicationRecord
  validates :description, presence: true
  validates :title, presence: true, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post
end

reddit/app/models/user.rb
class User < ApplicationRecord
  validates :password_digest, :session_token, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post

  def password=(password)
    @passord = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  private

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_logged_in

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_author, only: [:edit, :update]
  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    # debugger
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      @subs = Sub.all
      render :new
    end
  end

  def show
    return render :show if find_post

    flash[:errors] = ["Can't find post!"]
    redirect_to subs_url
  end

  def edit
    return render :edit if find_post

    flash[:errors] = ["Can't find post!"]
    redirect_to subs_url
  end

  def update
    find_post
    unless @post.update_attributes(post_params)
      flash[:errors] = @post.errors.full_messages
    else
      redirect_to post_url(@post)
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id[])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def require_author
    redirect_to subs_url unless current_user.posts.find_by(id: params[:id])
  end
end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username], user_params[:password]
    )

    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end

  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in
  before_action :require_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :show
    else
      flash[:errors] = ["Can't find that sub!"]
      redirect_to subs_url
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to sub_url(@sub)
    end
  end

  def destroy
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    redirect_to subs_url unless current_user.subs.find_by(id: params[:id])
  end
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">"
    html.html_safe
  end

  def submit(value)
    html = "<input type=\"submit\" value=\"#{value}\">"
    html.html_safe
  end
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
    <ul>
      <li><%= current_user.username %></li>
      <li><%= link_to "Create a sub!", new_sub_url %></li>
      <li><%= link_to "All Subs", subs_url %></li>
      <li><%= button_to "Logout", session_url, method: :delete %></li>
    </ul>
    <% else %>
      <%= link_to "Sign in!", new_session_url %>
    <% end %>
    <ul>
      <% flash[:errors].try(:each) do |error| %>
      <li><%= error %></li>
      <% end %>      
    </ul>
    <%= yield %>
  </body>
</html>

reddit/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

reddit/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

reddit/app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<form class="" action="<%= post_url %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>Content
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>
  </label>

  <input type="hidden" name="post[sub_id]" value="1">
  <%= submit("Submit") %>
</form>

reddit/app/views/posts/new.html.erb
<h1>New Post!</h1>

<form class="" action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>Content
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>
  </label>

  <ul>
    <% @subs.each do |sub| %>
    <label><%= sub.title %>
      <li><input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>"></li>
    </label>
  <% end %>
</ul>

  <%= submit("Submit") %>
</form>

reddit/app/views/posts/show.html.erb
<h1><%= link_to @post.title, post_url(@post) %> by <%= @post.author_username %></h1>

<p>Content: </p>
<br>
<p> <%= @post.content %> </p>

<h4>Subs</h4>
<ul>
  <li><%= link_to @post.sub.title, sub_url(@post.sub) %></li>
</ul>

<% if @post.author == current_user %>
  <%= link_to "Edit", edit_post_url(@post) %>
<% end %>

reddit/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

reddit/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

reddit/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

reddit/app/views/subs/edit.html.erb
<h1>Edit your Sub</h1>

<h1>Create a new sub!</h1>

<form class="" action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"><%= @sub.description %></textarea>
  </label>

  <%= submit("Submit!") %>
</form>

reddit/app/views/subs/index.html.erb
<h1>All the Subs!</h1>
<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>

reddit/app/views/subs/new.html.erb
<h1>Create a new sub!</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"><%= @sub.description %></textarea>
  </label>

  <%= submit("Submit!") %>
</form>

reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><strong>Description</strong></p>
<p><%= @sub.description %></p>

<%= link_to "Make New Post!", new_post_url %>

<br>
<ul>
  <% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>

<br>

<% if @sub.moderator == current_user %>
  <%= link_to 'Edit', edit_sub_url(@sub) %>
<% end %>

reddit/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

reddit/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

reddit/app/views/users/new.html.erb
<h1>New User!</h1>

<form class="" action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <%= submit("Sign Up") %>

</form>